[bumpversion]
commit=false
tag=false
message = 'Bump version: "{current_version}" → "{new_version}" ***NO_CI***'
# parse=(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\-(?P<release>[a-z]+)(?P<build>\d+))?
#serialize =
#    {major}.{minor}.{patch}-{release}{build}
#    {major}.{minor}.{patch}

#[bumpversion:file:VERSION]
#search = "{current_version}"
#replace = "{new_version}"

#[bumpversion:file:VERSION]
#search = "{current_version}"
#replace = "{new_version}"

#[bumpversion:files]
#path = "VERSION"
