[bumpversion]
commit = false
tag = false
message = 'Bump version: "{current_version}" → "{new_version}" ***NO_CI***'
search = "{current_version}"
replace = "{new_version}"


# [bumpversion:file:VERSION]
current_version = "9.0.18"
# [bumpversion:file:.bumpversion.toml]


[[files]]
path = "pyproject.toml"
