[bumpversion]
commit = false
tag = false
message = 'Bump version: "{current_version}" → "{new_version}" ***NO_CI***'

# [bumpversion:file:VERSION]
current_version = "9.0.18"
path = "pyproject.toml"
search = "{current_version}"
replace = "{new_version}"

[[files]]
path = "pyproject.toml"
