---
jobs:
  - job: Build_And_Test
    displayName: 'Build, Test and Publish the ***changeversion*** system.'
    steps:
      - task: InstallSSHKey@0
        displayName: "Install a private SSH key"
        inputs:
          knownHostsEntry: 'SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s'
          sshPublicKey: '$(id_rsa.pub)'
          sshKeySecureFile: 'id_rsa'
          sshPassphrase: 'yieks7dry'
      - task: Bash@3
        name: dependencies
        displayName: Install Dependencies
        inputs:
          targetType: 'inline'
          script: pip install tox pytest-azurepipelines
      - task: Bash@3
        name: tox
        displayName: 'TOX versions,tests,builds and publishes the artifact'
        inputs:
          targetType: 'inline'  
          workingDirectory: $(Build.Repository.LocalPath)
          script: tox
